services:
  openbucket-web:
    image: registry.appleby.cloud/openbucket-web:latest
    container_name: openbucket-web
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: "0.0.0.0"
      # API Configuration
      NEXT_PUBLIC_API_URL: http://openbucket-api:8003/core/v1
      API_URL: http://openbucket-api:8003/core/v1
      NPM_TOKEN: ${NPM_TOKEN}
    restart: unless-stopped
    networks:
      - openbucket-network
    healthcheck:
      test:
        - "CMD-SHELL"
        - "curl -f http://localhost:3000/api/health || exit 1"
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 45s
    depends_on:
      - openbucket-api
    labels:
      - "com.docker.compose.project=openbucket-web"
      - "traefik.enable=false" # Set to true if using Traefik

  openbucket-api:
    image: registry.appleby.cloud/openbucket-api:latest
    container_name: openbucket-api
    ports:
      - "8003:8003"
    environment:
      PORT: 8003
      JWT_SECRET: ${JWT_SECRET}
      CRYPTO_KEY: ${CRYPTO_KEY}
    restart: unless-stopped
    networks:
      - openbucket-network
    healthcheck:
      test:
        - "CMD-SHELL"
        - "wget --no-verbose --tries=1 --spider http://localhost:8003/health || exit 1"
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s
    labels:
      - "com.docker.compose.project=openbucket-web"
      - "traefik.enable=false" # Set to true if using Traefik

networks:
  openbucket-network:
    driver: bridge
    name: openbucket-network
