/**
 * Custom HTTPS server for local development only.
 *
 * This server is used to run the Next.js app with HTTPS locally,
 * which is required for Secure cookies to work across subdomains.
 *
 * DO NOT USE IN PRODUCTION - use your hosting platform's SSL termination instead.
 *
 * Prerequisites:
 * 1. Install mkcert: brew install mkcert && mkcert -install
 * 2. Generate certs: mkcert "*.local.appleby.cloud" local.appleby.cloud
 * 3. Add to /etc/hosts: 127.0.0.1 openbucket.local.appleby.cloud
 *
 * Usage: npm run dev:ssl
 */

/* eslint-disable @typescript-eslint/no-require-imports */
const { createServer } = require("https");
const { parse } = require("url");
const next = require("next");
const fs = require("fs");
const path = require("path");
/* eslint-enable @typescript-eslint/no-require-imports */

// Ensure this only runs in development
if (process.env.NODE_ENV === "production") {
	console.error(
		"ERROR: server.js is for local development only. Use `npm start` for production.",
	);
	process.exit(1);
}

const dev = true;
const hostname = "openbucket.local.appleby.cloud";
const port = 3010;

// SSL certificate paths
const certKeyPath = path.join(
	__dirname,
	"_wildcard.local.appleby.cloud+1-key.pem",
);
const certPath = path.join(__dirname, "_wildcard.local.appleby.cloud+1.pem");

// Verify SSL certificates exist
if (!fs.existsSync(certKeyPath) || !fs.existsSync(certPath)) {
	console.error("\n❌ SSL certificates not found!\n");
	console.error("Run the following commands to generate them:\n");
	console.error("  brew install mkcert");
	console.error("  mkcert -install");
	console.error('  mkcert "*.local.appleby.cloud" local.appleby.cloud\n');
	console.error("Or use: dev setup-ssl\n");
	process.exit(1);
}

// SSL certificates generated by mkcert
const httpsOptions = {
	key: fs.readFileSync(certKeyPath),
	cert: fs.readFileSync(certPath),
};

const app = next({ dev, hostname, port });
const handle = app.getRequestHandler();

app.prepare().then(() => {
	createServer(httpsOptions, async (req, res) => {
		try {
			const parsedUrl = parse(req.url, true);
			await handle(req, res, parsedUrl);
		} catch (err) {
			console.error("Error occurred handling", req.url, err);
			res.statusCode = 500;
			res.end("internal server error");
		}
	}).listen(port, () => {
		console.log(`> Ready on https://${hostname}:${port}`);
	});
});
