/**
 * Custom HTTPS server for local development only.
 *
 * This server is used to run the Next.js app with HTTPS locally,
 * which is required for Secure cookies to work across subdomains.
 *
 * DO NOT USE IN PRODUCTION - use your hosting platform's SSL termination instead.
 *
 * Prerequisites:
 * 1. Install mkcert: brew install mkcert && mkcert -install
 * 2. Generate certs: mkcert "*.local.appleby.cloud" local.appleby.cloud
 * 3. Add to /etc/hosts: 127.0.0.1 openbucket.local.appleby.cloud
 *
 * Usage: npm run dev:ssl
 */

/* eslint-disable @typescript-eslint/no-require-imports */
const { createServer } = require("https");
const next = require("next");
const fs = require("fs");
const path = require("path");
/* eslint-enable @typescript-eslint/no-require-imports */

// Ensure this only runs in development
if (process.env.NODE_ENV === "production") {
	console.error(
		"ERROR: server.js is for local development only. Use `npm start` for production.",
	);
	process.exit(1);
}

const dev = true;
const hostname = "openbucket.local.appleby.cloud";
const port = 3010;

// SSL certificate paths
const certKeyPath = path.join(
	__dirname,
	"_wildcard.local.appleby.cloud+1-key.pem",
);
const certPath = path.join(__dirname, "_wildcard.local.appleby.cloud+1.pem");

// Verify SSL certificates exist
if (!fs.existsSync(certKeyPath) || !fs.existsSync(certPath)) {
	console.error("\n❌ SSL certificates not found!\n");
	console.error("Run the following commands to generate them:\n");
	console.error("  brew install mkcert");
	console.error("  mkcert -install");
	console.error('  mkcert "*.local.appleby.cloud" local.appleby.cloud\n');
	console.error("Or use: dev setup-ssl\n");
	process.exit(1);
}

// SSL certificates generated by mkcert
const httpsOptions = {
	key: fs.readFileSync(certKeyPath),
	cert: fs.readFileSync(certPath),
};

// Load keyring secrets BEFORE initializing Next.js so NEXT_PUBLIC_* vars
// are available when the client bundle is compiled.
async function start() {
	// Load .env and .env.local since Node doesn't do it automatically (Next.js
	// loads them later, but we need KEYRING_* vars before Next initialises).
	// .env is loaded first, then .env.local can override values.
	for (const envFile of [".env", ".env.local"]) {
		const envPath = path.join(__dirname, envFile);
		if (fs.existsSync(envPath)) {
			const lines = fs.readFileSync(envPath, "utf8").split("\n");
			for (const line of lines) {
				const match = line.match(/^\s*([\w.-]+)\s*=\s*['"]?(.*?)['"]?\s*$/);
				if (match && !process.env[match[1]]) {
					process.env[match[1]] = match[2];
				}
			}
		}
	}

	if (process.env.KEYRING_URL) {
		const { Client } = require("@aidenappleby/keyring-js");
		const client = new Client();
		await client.injectEnv();
	}

	const app = next({ dev, hostname, port });
	const handle = app.getRequestHandler();

	await app.prepare();
	createServer(httpsOptions, async (req, res) => {
		try {
			await handle(req, res);
		} catch (err) {
			console.error("Error occurred handling", req.url, err);
			res.statusCode = 500;
			res.end("internal server error");
		}
	}).listen(port, () => {
		console.log(`> Ready on https://${hostname}:${port}`);
	});
}

start().catch((err) => {
	console.error("Failed to start server:", err);
	process.exit(1);
});
